### ISSUE TITLE
[TODO]: Prepare beta for USB upstreaming

### ISSUE THREAD

**Issue by CoMPaTech** [plugwise/plugwise-beta#362]
### Todo

Original text from #361 

Following https://plugwise.github.io/progress/diff.html

Adding `# pw-beta` tags where appropriate to ease up differences

PR is also meant as a step-up to see if we can carve out a way for the Core Team to decide on embedding USB into the Core Plugwise environment. E.g. making sure the 'mammoth' that is now https://plugwise.github.io/progress/diff.html can be used as an oversight and from that we can chunk PRs in a relative quick pace to ensure we embed USB within a month between releases. As such re-breathing live into Core PR 35713 

Checklist as per [Progress diff core/beta](https://plugwise.github.io/progress/diff.html) beginning of March 2023: (note that all `COORDINATOR` relations are under `coordinator.py` to not re-iterate across all domains)

- [x] **USB** `plugwise/__init__.py` replaces placeholders when upstreaming
- [ ] __Generic__/**USB** `plugwise/binary_sensor.py``dataclass` structure needs conformance/decision between beta and core
- [x] __Generic__ `plugwise/climate.py` though mainly 'options' which won't upstream
- [x] **USB** `plugwise/config_flow.py` foremost USB flow handling + some exceptions
- [ ] __Generic__/**USB** `plugwise/const.py` const & dataclass
- [ ] __Generic__ `plugwise/coordinator.py` untouched, needs alignment between beta and core
- [x] __Generic__ `plugwise/diagnostics.py` *) except coordinator
- [x] __Generic__ `plugwise/entity.py` only isorted
- [x] __Generic__ `plugwise/gateway.py` mostly beta-only related things
- [x] __Generic__ `plugwise/manifest.json` no actions needed specifically
- [ ] __Generic__ `plugwise/number.py` needs alignment
- [x] __Generic__ `plugwise/select.py` *) except coordinator
- [ ] __Generic__/**USB** `plugwise/sensor.py` `dataclass` structure needs conformance/decision between beta and core
- [x] **USB** `plugwise/strings.json` 
- [x] **USB** `plugwise/switch.py` 
- [ ] __Generic__ `plugwise/util.py`

(not in #361) This also depends on [python-plugwise issue 131](https://github.com/plugwise/python-plugwise/issues/131) to have more proper testing involved, but we might leverage community effort there as well once we have upstream in place.
